version: "3"
services:
  ganache:
    build:
      context: .
      dockerfile: Dockerfile.ganache
    ports:
      - "8545:8545"
  dapp:
    build: .
    ports: 
      - "4000:4000"
    volumes:
      - /app/node_modules
      - .:/app